Sprint03 us23 creation produits photos
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #105
Opened 2019-04-27 10:33 UTC by vincent-mouline

2019-04-27 10:34 UTC, foforato reviewed
ok

2019-04-28 22:24 UTC, sblondeau requested changes
toutes les images uploadables ne doivent pas etre versionnées !
il faut ajouter les images de ce dossier dans gitignore et les déversionner via git rm --cached

2019-04-28 22:24 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +                    $errors['picture'] = '8 photos maximum';
tu as fais une variable $maxPictures, utilises là aussi dans le message d'erreur

2019-04-29 07:22 UTC, foforato approved these changes
ok

2019-04-29 07:24 UTC, sblondeau approved these changes

2019-04-29 07:24 UTC, merged