add delete method for ProductManager and PictureManager
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #113
Opened 2019-04-27 13:14 UTC by vincent-mouline

2019-04-27 13:18 UTC, vincent-mouline commented
La suppression locale des fichiers feront partie d'une autre User Story

2019-04-27 13:20 UTC, foforato approved these changes

2019-04-28 22:29 UTC, sblondeau requested changes

2019-04-28 22:29 UTC, sblondeau commented on src/Model/PictureManager.php
> +        $query = "DELETE FROM $this->table WHERE `product_id`=$id";
tu dois aussi gérer la suppression du fichier stocké sur le serveur (sinon tu risques de saturer le disque dur si les images que tu supprimes via le site ne sont pas vraiment supprimées).
Bref, il faut que tu récupère le path vers le fichier et que tu fasses un unlink($path)

2019-04-28 22:29 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +        $pictureManager = new PictureManager();
tjs en POST la deletion, donc tu dois avoir un if ($_SERVER[...] == POST) pour commencer la méthode, et un form dans la vue

2019-04-28 22:29 UTC, sblondeau commented on src/View/Admin/products.html.twig
> +                    <td><a href="/adminProduct/delete/{{ product.id }}"><img src="/assets/images//delete-filled.png"></a></td>
faire un form à la plate du lien, sinon faille de sécurité

2019-04-29 09:33 UTC, foforato approved these changes
ok

2019-04-29 10:17 UTC, sblondeau approved these changes

2019-04-29 10:18 UTC, merged

2019-04-29 11:16 UTC, foforato reviewed
ok