Sprint03 us19 recherche
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #123
Opened 2019-04-29 14:14 UTC by laheravilla

2019-04-29 14:18 UTC, foforato approved these changes

2019-04-29 19:32 UTC, sblondeau requested changes

2019-04-29 19:32 UTC, sblondeau commented on src/Controller/ProductController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
le form de recherche se font plutot en GET

2019-04-29 19:32 UTC, sblondeau commented on src/View/_navbar.html.twig
> +            <form class="form-inline my-2 my-lg-0 justify-content-center" method="post" action="product/search">
method="GET"

2019-04-30 06:42 UTC, foforato approved these changes

2019-04-30 06:59 UTC, sblondeau approved these changes

2019-04-30 06:59 UTC, sblondeau requested changes

2019-04-30 06:59 UTC, sblondeau commented on src/Controller/ProductController.php
> +            $name = $_POST['search_box'];
tu clean $_GET donc ici c'est $name = $data['serach_box'] plutot non ?

2019-04-30 08:23 UTC, sblondeau approved these changes

2019-04-30 09:32 UTC, merged