Random items on the product page
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #129
Opened 2019-04-29 15:34 UTC by laheravilla

2019-04-29 15:35 UTC, foforato approved these changes

2019-04-29 19:34 UTC, sblondeau requested changes

2019-04-29 19:34 UTC, sblondeau commented on src/View/Item/showItem.html.twig
> +            <div class="card col-lg-4 col-sm-8 col-md-4 mx-auto">
non, il faut faire un boucle 
{%for itemRandom in itemsRandom %}
...
et comme ça tu n'as pas à répéter 3 fois le code HTML ;-)

2019-04-29 20:18 UTC, foforato approved these changes

2019-04-30 07:00 UTC, sblondeau approved these changes

2019-04-30 07:00 UTC, merged