creation page notre produit
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #132
Opened 2019-04-29 17:04 UTC by foforato

2019-04-29 18:35 UTC, vincent-mouline approved these changes

2019-04-29 19:38 UTC, sblondeau requested changes

2019-04-29 19:38 UTC, sblondeau commented on src/Controller/NotreBoutiqueController.php
> +class NotreBoutiqueController extends AbstractController
NOOOON ! je ne comprends pas qu'on puisse perdre encore du temps sur ce type d'erreur de nommage. En anglais please !

2019-04-29 19:38 UTC, sblondeau commented on src/View/Home/index.html.twig
> +    {% include "Item/_fonctionnementDepotVente.html.twig" %}
idem les noms de fichiers de template, en anglais...

2019-04-29 19:38 UTC, sblondeau commented on src/View/Item/_fonctionnementDepotVente.html.twig
> +    <h4 class="fonctionnementdepotvente" id="fonctionnement">Fonctionnement du depot vente</h4>
dépôt

2019-04-29 19:38 UTC, sblondeau commented
le PO devrait voir ce type d'erreur au passage...

2019-04-30 08:24 UTC, sblondeau approved these changes

2019-04-30 08:24 UTC, merged