add delete for category administration
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #133
Opened 2019-04-29 18:38 UTC by vincent-mouline

2019-04-29 18:47 UTC, foforato approved these changes

2019-04-29 19:39 UTC, sblondeau requested changes

2019-04-29 19:39 UTC, sblondeau commented on src/Model/CategoryManager.php
> +        $query = "DELETE FROM $this->table WHERE `id`=$id";
requête préparée please

2019-04-30 08:08 UTC, foforato approved these changes

2019-04-30 08:25 UTC, sblondeau approved these changes

2019-04-30 08:25 UTC, merged