Sprint01 us02 jumbotron
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #14
Opened 2019-04-12 11:50 UTC by laheravilla

2019-04-12 12:03 UTC, beegeebuzz requested changes

2019-04-12 12:03 UTC, beegeebuzz commented on src/View/Home/index.html.twig
> +                <!--  <a class="btn btn-outline-white btn-md"><i class="fas fa-clone left"></i> View project</a> -->
Pas de code commenté,
soit la fonction est présente et  fonctionnelle,
soit la fonction n'existe pas.

2019-04-12 12:06 UTC, sblondeau requested changes
pense à réduire la taille de l'image, 500ko c'est trop. Passe déjà l'image en jpg tu devrais beaucoup gagner

2019-04-12 12:06 UTC, sblondeau commented on public/assets/css/style.css
> +    font-size: 50pt!important;
pas de !important, c'est une mauvaise pratiqeu

2019-04-12 12:06 UTC, sblondeau commented on public/assets/css/style.css
> +    margin-bottom: 0!important;
idem et plus bas aussi

2019-04-12 12:06 UTC, sblondeau commented on public/assets/css/style.css
> +@media screen and (max-width: 800px) {
ne commencez pas à me mettre des media-queries à tout va. Normalement avec Bootstrap ça suffit pour gérer les choses proprement

2019-04-12 12:06 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                <!--  <a class="btn btn-outline-white btn-md"><i class="fas fa-clone left"></i> View project</a> -->
pas de code commenté

2019-04-12 12:06 UTC, sblondeau commented on src/View/layout.html.twig
> +{% block jumbotron %}{% endblock %}
si tu n'as qu'un block jumbotron pour cette seule page, pas la peine de créer ici un block dédié

2019-04-12 15:09 UTC, beegeebuzz approved these changes
All is right

2019-04-15 09:42 UTC, open-it approved these changes

2019-04-15 09:42 UTC, merged