add update product forms
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #141
Opened 2019-04-30 10:58 UTC by vincent-mouline

2019-04-30 10:59 UTC, foforato approved these changes

2019-04-30 11:35 UTC, sblondeau requested changes

2019-04-30 11:35 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +    public function update()
non là l'id passe en paramètre de l'update et passe donc ds ta route
/adminProduct/update/5 par ex

2019-04-30 11:35 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'GET') {
donc pas besoin du GET ici

2019-04-30 11:35 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +                header('location: /AdminProduct/confirmAdding');
exit() après le header Location

2019-04-30 11:35 UTC, sblondeau commented on src/View/Admin/add.html.twig
> +                <label for="id">
pas de label pour un input hidden puisque par définition, il est caché

2019-04-30 11:35 UTC, sblondeau commented on src/View/Admin/add.html.twig
> +        <form class="form-row" {% if id is not null %}action="/adminProduct/update"
mais en fait si tu laisse le action="" (vide) par défaut il revient sur la page en cours, donc tu n'as pas besoin de cette condition

2019-04-30 11:35 UTC, sblondeau commented on src/View/Admin/products.html.twig
> +                    <form method="get" action="/AdminProduct/update/">
et là le lien qui envoie vers la page d'update, comme je te disais un 
`<a href="/AdminProduct/{{product.id}}">` suffit

2019-04-30 20:18 UTC, foforato approved these changes

2019-05-01 07:44 UTC, sblondeau approved these changes

2019-05-01 07:44 UTC, merged