Sprint01 us01 navbar
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #15
Opened 2019-04-12 12:19 UTC by Foo-Vinny

2019-04-12 12:32 UTC, beegeebuzz requested changes

2019-04-12 12:32 UTC, beegeebuzz commented on src/View/_navbar.html.twig
> +
Suppression catégories

2019-04-12 14:21 UTC, beegeebuzz approved these changes
All is right

2019-04-15 08:32 UTC, open-it requested changes

2019-04-15 08:32 UTC, open-it commented on .gitignore
> +idées site
pas de dossiers avec des espaces, accents etc...

2019-04-15 08:32 UTC, open-it commented on public/assets/css/style.css
> +/* text centered on burger navigation */
attention aux commentaires, ils ne sont pas interdit mais sont ils vraiment utile ?

2019-04-15 08:48 UTC, foforato approved these changes
Les commentaires sont supprimés, le dossier enlevé

2019-04-15 10:04 UTC, open-it approved these changes

2019-04-15 10:04 UTC, merged