Sprint02 us4 card
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #52
Opened 2019-04-16 15:59 UTC by JessFromThePampa

2019-04-16 16:01 UTC, foforato approved these changes
ok

2019-04-16 16:43 UTC, sblondeau requested changes

2019-04-16 16:43 UTC, sblondeau commented on src/View/_card.html.twig
> +                {% endfor %}
ton endfor est mal mis, il devrait se ferme sur la ligne au dessus

2019-04-16 16:43 UTC, sblondeau commented on src/View/_card.html.twig
> +                    {%  for picture in pictures %}
tu affiches toutes les pictures pour chaque product là, je pense qu'il y a un soucis

2019-04-17 08:55 UTC, foforato approved these changes
OK

2019-04-17 08:59 UTC, sblondeau requested changes

2019-04-17 08:59 UTC, sblondeau commented on src/View/_card.html.twig
> +                        <a href="/products/show/{{ product.id }}" class="btn">+ d'infos</a>
hum je pense que vous n'utilisez pas bien bootstrap
pour un bouton c'est btn et btn-unStatus
là vous avez surchargé juste btn dans le CSS et pas ajouter la classe btn-quelquchose
vous pouvez aussi vous créer une class btn-autrechose avec votre couleur perso, ou surcharger btn-primary et btn-secondary avec vos couleurs. Bref plein de possibilité mais pas comme ça. Et du coup pas de btn2 comme 5 lignes en dessous

2019-04-17 08:59 UTC, sblondeau commented on public/assets/css/style.css
> +.section1 {
j'aime pas ce nom de classe. Essayez de garder des noms compréhensibles

2019-04-17 12:00 UTC, sblondeau approved these changes

2019-04-17 12:03 UTC, foforato approved these changes
Conflit ok

2019-04-17 13:14 UTC, merged