Sprint02 us10 gestion produits
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #57
Opened 2019-04-17 13:39 UTC by vincent-mouline

2019-04-17 13:41 UTC, foforato approved these changes
ok

2019-04-17 15:39 UTC, sblondeau requested changes

2019-04-17 15:39 UTC, sblondeau commented on src/Model/ProductManager.php
> +        return $this->pdo->query("SELECT product.id, product.name, product.price, product.date_added,
appelle plutot la methode showAllWithCategories() ça serait plus parlant, car si tu join product à une autre table plus tard, tu seras embeté ;-)
et sinon déporte ta requete dans une variable $query et n'hésite pas à l'écrire sur plusieurs lignes, par ex
```
$query = "SELECT * FROM myTable
                   JOIN otherTable ...
                WHERE champ=truc";
``` 
ça sera beaucoup plus lisible !

2019-04-17 15:39 UTC, sblondeau commented on src/View/Admin/products.html.twig
> +                        <div class="custom-control custom-switch">
comme on a dit tout à l'heure, pour l'instant enlève ces boutons switch et garde ça pour une future PR (avec de l'ajax). Pour l'instant, tu le géreras dans la page d'edit de chaque produit

2019-04-17 15:39 UTC, sblondeau commented on src/View/Admin/products.html.twig
> +                    <td><a href="/adminProduct/update"><img src="https://img.icons8.com/ios/25/000000/edit-filled.png"></a></td>
télécharge l'image en local c'est mieux que de reposer sur un site externe, qui peut enlever l'image à tout moment

2019-04-17 20:44 UTC, sblondeau requested changes
les images des icones sont beaucoup trop lourdes. Ca ne devrait faire que quelques ko. Déjà les passer en JPG devrait bien arranger les choses

2019-04-17 20:44 UTC, sblondeau commented on src/Model/ProductManager.php
> +                    inner join bannier.category
tous les mots clés de SQL s'écrivent plutot en majuscule (INNER JOIN, ON, ORDER BY...)

2019-04-17 20:44 UTC, sblondeau commented on src/Model/ProductManager.php
> +        $query = "SELECT product.id,
tu peux écrire tous les champs du select sur une meme ligne par contre sinon ça fait très long ;-)
SELECT champ1, champ2, champ3, ... FROM table
JOIN table2 ON ...
ORDER BY ...

2019-04-23 10:12 UTC, sblondeau requested changes

2019-04-23 10:12 UTC, sblondeau commented on src/Model/ProductManager.php
> +        $query = "SELECT product.id,
je suis dsl mais ces remarques sur la façon d'écrire la requete n'ont pas été prises en compte

2019-04-23 10:19 UTC, vincent-mouline commented
Désolé, je pensais avoir push les modifications demandes. Ce n'etait pas le cas , erreurs corrigées

2019-04-23 12:52 UTC, sblondeau approved these changes

2019-04-23 13:05 UTC, JessicaSalvat approved these changes
Ok

2019-04-23 13:13 UTC, merged