Sprint02 us4 card
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #58
Opened 2019-04-17 13:57 UTC by JessFromThePampa

Le code commenté " {#{% for product in products %}#}" est pour éviter les problème d'affichage en attendant la bdd.

2019-04-17 13:57 UTC, foforato approved these changes
ok

2019-04-17 20:45 UTC, sblondeau requested changes

2019-04-17 20:45 UTC, sblondeau commented on src/View/Item/_card.html.twig
> +        {#{% for product in products %}#}
tu ne dois pas avoir de code commenté, sinon c'est que ton US n'es pas finie !
si tu as besoin de recup les produits pour finir ta PR, tu dois utiliser la méthode qui va bien du ProductManager

2019-04-24 09:41 UTC, foforato approved these changes
ok

2019-04-24 11:17 UTC, sblondeau requested changes

2019-04-24 11:17 UTC, sblondeau commented on src/Controller/HomeController.php
> +
pourquoi un tableau "var" ? il faut passer direct categories et products

2019-04-24 11:17 UTC, sblondeau commented on src/View/Home/index.html.twig
> +            {% for product in var.products|slice (0,3) if product.ahead == 1 %}
si tu ne dois en afficher que 3, il faut plutot que tu fasse une LIMIT au niveau de ta requete SQL, bien plus performant

2019-04-24 13:40 UTC, foforato approved these changes
ok

2019-04-24 13:55 UTC, sblondeau approved these changes

2019-04-24 13:59 UTC, foforato approved these changes
ok

2019-04-24 14:01 UTC, foforato approved these changes
ok

2019-04-24 14:31 UTC, merged