Sprint02 us05 formulaire contact accueil
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #62
Opened 2019-04-23 15:25 UTC by laheravilla

2019-04-23 15:25 UTC, JessFromThePampa commented
Ok :)

2019-04-24 07:30 UTC, JessicaSalvat approved these changes
Ok

2019-04-24 09:34 UTC, sblondeau requested changes

2019-04-24 09:34 UTC, sblondeau commented on src/View/Item/_formContact.html.twig
> +                            <input type="text" class="form-control" id="name" aria-describedby="inputGroupPrepend" name="name" value="{{ data.name|striptags ? '' }}" required>
pas besoin des striptags

2019-04-24 09:34 UTC, sblondeau commented on src/utils/CleanData.php
> +            $cleanData[$datum] = strip_tags(stripslashes(trim($value)));
que un trim ici, pas le reste ! car sinon ça influe sur la taille de tes values

2019-04-24 09:40 UTC, JessicaSalvat approved these changes
Ok

2019-04-24 11:19 UTC, sblondeau approved these changes

2019-04-24 13:52 UTC, JessicaSalvat approved these changes
Ok conflit merge resolu

2019-04-24 13:52 UTC, merged