Sprint03 us17 nos produits
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #82
Opened 2019-04-25 11:50 UTC by vincent-mouline

2019-04-25 11:52 UTC, foforato approved these changes
YES

2019-04-25 14:14 UTC, sblondeau requested changes

2019-04-25 14:14 UTC, sblondeau commented on src/Controller/ProductsController.php
> +class ProductsController extends AbstractController
ProductController
Les noms de class (controller ou manager...) tjs au singulier !

2019-04-25 14:14 UTC, sblondeau commented on src/Controller/ProductsController.php
> +    public function categories(int $id)
un nom de methode est un verbe donc "categories" ne va pas

d'autre part, il faut que ta PR ne fasse qu'une chose. Donc tu ne peux pas avoir deux render dans une meme PR car tu ne peux pas afficher 2 pages d'un coup ;-) donc à simplifier. D'autre part, j'ai un peu de mal à comprendre la différence entre index() et categories() ici

2019-04-25 14:14 UTC, sblondeau commented on src/Model/ProductManager.php
>      public function showAllWithPictures(): array
je ne suis pas sur de ce que tu souhaites faire ici et je pense que tu t'y prends mal, on en discute

2019-04-25 14:14 UTC, sblondeau commented on src/Model/ProductManager.php
> +        $query = "SELECT product.*
il ne faut pas mettre tout à la ligne systématiquement dans tes requetes, et joue sur l'indentation pour que ce soit plus lisible.
Tu peux aussi omettre le mot clé INNER

2019-04-25 14:53 UTC, sblondeau commented
j'ai une ou deux modifs mais y en a plein qui ne sont pas corrigées... dans ce cas ça ne sert à rien de remettre "reviewed by PO" ... :/

2019-04-26 07:51 UTC, vincent-mouline commented on src/Controller/ProductsController.php
> +    public function categories(int $id)
J'avais créé deux méthodes au cas ou le client souhaitait afficher toutes les catégories ( index ) ou sélectionner une catégorie en particulier . c'est réglé désormais.

2019-04-26 08:20 UTC, foforato approved these changes
OK

2019-04-26 17:53 UTC, foforato approved these changes
ok

2019-04-28 22:14 UTC, sblondeau approved these changes

2019-04-28 22:14 UTC, sblondeau commented on src/Model/ProductManager.php
> +        $query = "SELECT DISTINCT pr.id, pr.name, pr.price,  pr.description, pr.ahead ,min(pi.name) AS picture
ce n'est pas tout à fait ça que j'avais en tête, le DISTINCT semple etre inutile ici ? mais bon il faudrait tester... on a plus trop le temps, si ça marche on va passer comme ça

2019-04-28 22:14 UTC, merged