Fixes02
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #85
Opened 2019-04-25 14:24 UTC by vincent-mouline

2019-04-25 14:25 UTC, foforato approved these changes
ok

2019-04-25 14:55 UTC, sblondeau commented
c'est sur master et non dev !!! un gateau pour demain ;-)

2019-04-26 06:47 UTC, sblondeau requested changes

2019-04-26 06:47 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                        <strong>Depot-Vente Bannier</strong></h2>
Dépôt

2019-04-26 06:47 UTC, sblondeau commented on src/View/Item/_footer.html.twig
>                  <p class="pb-5"><br> 104 rue du Faubourg Bannier <br> 45000 ORLEANS <br>
balise `<address>` plutot que `<p>`
https://developer.mozilla.org/fr/docs/Web/HTML/Element/address

2019-04-26 07:25 UTC, foforato commented on src/View/Item/_footer.html.twig
>                  <p class="pb-5"><br> 104 rue du Faubourg Bannier <br> 45000 ORLEANS <br>
j'ai modifie la balise p en baslise adress dans la précédente PR "notreboutique"

2019-04-26 07:31 UTC, sblondeau approved these changes

2019-04-26 07:31 UTC, merged