Sprint03 us18 page produit
WildCodeSchool/orleans-0219-php-depot-vente-bannier pull request #90
Opened 2019-04-26 15:21 UTC by laheravilla

2019-04-26 15:36 UTC, foforato approved these changes
ok

2019-04-28 22:21 UTC, sblondeau requested changes

2019-04-28 22:21 UTC, sblondeau commented on src/Controller/ProductsController.php
> +    public function categories($id)
index() et categories() font la meme chose + ou - le filtre par $id non ?
du coup il ne faudrait garder qu'une des deux, et gérer le fait que si $id est null, la requête effectuée corresponde à un selectAll()

2019-04-28 22:21 UTC, sblondeau commented on src/Model/ProductManager.php
> +    public function showRandom(): array
ça devrait etre dans une autre PR non ?

2019-04-28 22:21 UTC, sblondeau commented on src/Model/ProductManager.php
> +                    INNER JOIN bannier.picture
la jointure me semble inutile ici
juste une SELECT id, name FROM picture WHERE product_id=$id  devrait etre suffisant, non ?

2019-04-28 22:21 UTC, sblondeau commented on src/Model/ProductManager.php
> +                   INNER JOIN bannier.category
il faut enlever le préfixe "bannier." partout (prévoir un fix éventuellement) car on ne doit pas imposer le nom de la BDD, seulement le nom des tables

2019-04-29 10:14 UTC, sblondeau approved these changes

2019-04-29 10:14 UTC, merged